name: Test

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '45 1 * * *'

jobs:

  test:
    runs-on: ${{ matrix.os }}

    env:
      latest_php: 8.3
      latest_laravel: 11

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        php: [ '8.1', '8.2', '8.3' ]
        laravel: [ 10, 11 ]
        exclude:
          - php: 8.1
            laravel: 11

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=E_ALL
          tools: composer:v2

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 30
          max_attempts: 3
          command: |
            composer require "illuminate/log=^${{ matrix.laravel }}" --no-update --no-plugins
            composer install --quiet --no-plugins --no-ansi --prefer-dist --no-progress --no-interaction

      - name: Migrate phpunit XML configuration
        run: vendor/bin/phpunit --migrate-configuration || true

      - name: Run test suite
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: false
        if: matrix.php == env.latest_php && matrix.laravel == env.latest_laravel
